### ISSUE TITLE
프로필 기본 이미지 필요

### ISSUE THREAD

**Issue by JaeBeen95** [travelly-8/travelly-fe#291]
## 설명

> ![image](https://github.com/travelly-8/travelly-fe/assets/108844881/cf0f5b77-a07a-4090-b466-0c1eded9beb3)

## TO DO

- [ ] 할 일 1

## 기타

> -

**Comment by innerstella** [comment]
이 부분 제가 원준님께 말씀 드려서 한 번 고쳤었는데, 다시 한 번 확인해볼게요!

**Comment by innerstella** [comment]
![image](https://github.com/travelly-8/travelly-fe/assets/77491430/3c56cf9b-196b-4939-b90d-3ce26eb83c78)

제가 신규 가입하고 확인했는데 기본 이미지 잘 뜹니다...!

혹시 어떤 케이스인지 조금 더 자세히 설명해주실 수 있으신가요?

**Comment by JaeBeen95** [comment]
> ![image](https://private-user-images.githubusercontent.com/77491430/342098504-3c56cf9b-196b-4939-b90d-3ce26eb83c78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxODc3NzksIm5iZiI6MTcxOTE4NzQ3OSwicGF0aCI6Ii83NzQ5MTQzMC8zNDIwOTg1MDQtM2M1NmNmOWItMTk2Yi00OTM5LWI5MGQtM2NlMjZlYjgzYzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAwMDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMWEzNzU3MDRjYTM3YWI5YTI5YjYzMzVhY2M5NDUxODljOGEyNTNiOTNhYTFmNjUxYTk1NWRkYjlkMTQ4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uffS_gQqTmnj-m3vMTZekSCk-ypODekduMLwmb13Wls)
> 
> 제가 신규 가입하고 확인했는데 기본 이미지 잘 뜹니다...!
> 
> 혹시 어떤 케이스인지 조금 더 자세히 설명해주실 수 있으신가요?

아마 이전 데이터라서 깨지는 현상이 발생한 거 같아요 지금 가입하니 괜찮네요!

다만 찾아보다 발견한 게 있는데 

<img width="260" alt="배포환경 이미지 깨짐" src="https://github.com/travelly-8/travelly-fe/assets/108844881/d1601045-f2cb-43f0-b379-3db2457d267f">

배포환경에서 요렇게 이미지가 깨지네요..!

**Comment by innerstella** [comment]
앗 이부분 이슈 열어서 해결하겠습니다!
